### ISSUE TITLE
Known Issue: containers.podman is required for this collection, but not a dependency 

### ISSUE THREAD

**Issue by myllynen** [redhat-cop/ee_utilities#135]
When doing "ansible-galaxy collection install infra.ee_utilities" the required containers.podman collection is not installed as a dependency because it is not listed as such in galaxy.yml.

**Comment by sean-m-sullivan** [comment]
This is a known issue atm. If we include it in galaxy.yml, it would install normally. However if someone tries to pull the collection from Console.redhat.com, Because containers.podman is not in the validated repository, it fails, Keeping this open to document it, but it requires fixes on automation hub/console.redhat backend.

**Comment by extravio** [comment]
In Ansible Hub, we can synchronize collections that have dependencies in different remotes by specifying a **source** in the requirements.yml file.
example: 
```yaml
collections:
  - name: network.base
    source: https://console.redhat.com/api/automation-hub/content/validated/

  - name: network.interfaces
    source: https://console.redhat.com/api/automation-hub/content/validated/

  - name: ansible.utils
    source: https://console.redhat.com/api/automation-hub/content/published/

  - name: ansible.netcommon
    source: https://console.redhat.com/api/automation-hub/content/published/
```
see: [How to sync Validated Ansible Collections from console.redhat.com to Private Automation Hub using a requirements.yml file?](https://access.redhat.com/solutions/7051030)

However, specifying the following did not work for us:
```yaml
collections:
  - name: containers.podman
    source: https://galaxy.ansible.com/api/
  - name: infra.ee_utilities
    source: https://console.redhat.com/api/automation-hub/content/validated/ 
```

Is there something you can change at your end that would prevent Automation Hub from trying to pull containers.podman from  console.redhat and use the source specified in the requirements.yml file? @sean-m-sullivan
