### ISSUE TITLE
delegate_to: localhost prevents running on a remote machine

### ISSUE THREAD

**Issue by arjanhak** [redhat-cop/ee_utilities#148]
# Summary

I created a playbook that runs the infra.ee_utilities.ee_builder on a remote host, but I cannot use the ee_create_controller_def as part of the block are wrongfully executed on localhost.

# Issue Type

- Bug Report

# Ansible, Collection, Docker/Podman details

```
$ ansible --version
ansible [core 2.15.9]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/myuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/myuser/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.16 (main, Sep 12 2023, 00:00:00) [GCC 11.3.1 20221121 (Red Hat 11.3.1-4)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True


$ ansible-galaxy collection list

# /home/myuser/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
containers.podman  1.12.0
infra.ee_utilities 3.1.3


$ podman --version
podman version 4.6.1
```

- ansible installation method: OS package

# OS / ENVIRONMENT

# Desired Behavior

When I have a playbook that runs on a remote machine, I want to use the set_stats module to export the execution environment(s) meta information to the infra.controller_configuration.execution_environments role.

# Actual Behavior

Task "Create temporary folder" in roles/ee_builder/tasks/main.yml successfully creates the temporary directory on the remote machine, I can see it there. But the next task "Create execution environment definition file" fails because the directory does not exist **on localhost**.
If the "delegate_to: localhost" had not been there (also for the next task below it) then it would have worked afaik.

```
TASK [infra.ee_utilities.ee_builder : Create temporary folder] *****************
changed: [server.domain.com]
TASK [infra.ee_utilities.ee_builder : Create execution environment definition file] ***
fatal: [server.domain.com -> localhost]: FAILED! => {"changed": false, "checksum": "fe4ede2cc72683c7e3afecc329685a9ab072c0ac", "msg": "Destination directory /tmp/ansible.elb4u1k7temp does not exist"}
```

# STEPS TO REPRODUCE

```
---
- name: Playbook to create custom Execution Environment(s)
  hosts: server.domain.com
  gather_facts: false
  collections:
    - infra.ee_utilities

  vars:
    ...
    ee_create_controller_def: true
    ee_list:
	  ...

  tasks:
    ...

    - name: "Include role infra.ee_utilities.ee_builder"
      include_role:
        name: infra.ee_utilities.ee_builder

    ...
```
