### ISSUE TITLE
ee_builder concatenates the url and token into a siingle line in the generated ansible.cfg file.

### ISSUE THREAD

**Issue by binbashroot** [redhat-cop/ee_utilities#189]
## Summary

When using the infra.ee_utilities.ee_builder the generated ansible.cfg concatenates the url and token into a single line. The build will faiili because it cannot download the collections.  If I build it manually using the same generated ansible.cfg fiile it will also fail the build.  If I correct the ansible.cfg and run ansible-builder, the image will build fine. 

## Issue Type

- Bug Report

## Ansible, Collection, Docker/Podman details

```console (paste below)
ansible --version
ansible [core 2.16.14]
  config file = /home/foo/builder.v3/ansible.cfg
  configured module search path = ['/home/foo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.13/site-packages/ansible
  ansible collection location = /home/foo/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.13.2 (main, Feb  4 2025, 00:00:00) [GCC 14.2.1 20250110 (Red Hat 14.2.1-7)] (/usr/bin/python3)
  jinja version = 3.1.5
  libyaml = True


ansible-galaxy collection list
Collection                               Version     
---------------------------------------- ------------
ansible.controller                       4.6.3       
ansible.eda                              2.2.0       
ansible.hub                              1.0.0       
ansible.platform                         2.5.20250213
ansible.posix                            1.5.4       
ansible.utils                            5.1.2       
binbashroot.deploy_aap24                 1.0.0       
binbashroot.deploy_aap25                 1.0.0       
binbashroot.ocp_on_proxmox               1.0.17      
binbashroot.provision                    1.0.33      
community.crypto                         2.22.3      
community.general                        10.1.0      
community.routeros                       3.4.0       
infra.aap_configuration                  3.1.0       
infra.ah_configuration                   2.1.0       
infra.controller_configuration           2.11.0      
infra.ee_utilities                       4.0.0       
infra.leapp                              1.4.1       
redhat.rhel_system_roles                 1.88.9      
redhat.satellite                         5.0.0       
redhat.satellite_operations              3.0.0       
redhat_cop.controller_configuration      2.3.1       


podman --version
podman version 5.4.0

```

- ansible installation method: one of source, pip, OS package, EE

## OS / ENVIRONMENT

Fedora release 41 (Forty One)

## Desired Behavior

Running ansible-playbook to execute the infra.ee_utiils.ee_builder role should yield an EE that is pushed to Automation hub

## Actual Behavior
Playbook fails with an error and the url and token are on a single line in the generated ansible.cfg file

```
# deploy_custom_ee.yml playbook
---
- name: Custom Execution Environment Builder
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    ee_validate_certs: false
    ee_base_registry_username: "{{ lookup('env', 'CONTROLLER_ADMIN_USER') }}"
    ee_base_registry_password: "{{ lookup('env', 'CONTROLLER_ADMIN_PASS') }}"
    ee_base_image: aap.example.com/ansible-automation-platform-25/ee-supported-rhel9:latest
    ee_registry_dest: aap.example.com/binbashroot
    ee_registry_username: "{{ lookup('env', 'CONTROLLER_ADMIN_USER') }}"
    ee_registry_password: "{{ lookup('env', 'CONTROLLER_ADMIN_PASS') }}"
    ee_ah_host: aap.example.com
    ee_ah_token: "{{ lookup('env', 'HUB_TOKEN') }}"     
    ee_builder_dir_clean: false
    ee_builder_dir: "."
    ee_image_push: true
    ee_pull_collections_from_hub: true
    ee_update_base_images: true
    ee_verbosity: 3
    ee_list:
      - name: aap-test-cms-ee-supported-rhel9:{{ ee_tag | default('v2.0') }}
        alt_name: AAP CMS SUPPORTED RHEL9 EE       
        images:
          base_image: 
            name: aap.example.com/ansible-automation-platform-25/ee-supported-rhel9:latest
        dependencies:     
          ansible_core:
            package_pip: ansible-core>=2.15.13
          ansible_runner:
            package_pip: ansible-runner
          system:
            - tar
            - unzip
            - bzip2
            - nmap
            - gcc
            - systemd-devel
            - python3-devel
            - python3.11-devel
            - libxml2-devel
            - libxslt-devel

          python: 
            - proxmoxer>=1.3.1
            - netaddr>=0.8.0
            - urllib3>=1.26.12
            - cryptography>=41.0.6
            - pyopenssl>=23.1.0
            - awxkit
            - pytz
            - python-dateutil
          galaxy:
            collections:
              - community.general
              - community.crypto
              - community.dns
#       build_items:
#         - files/
        build_files:
          - src: files/ansible.cfg
            dest: configs 
        build_steps:
          prepend_base:
            - RUN echo This is the prepend base command
          prepend_galaxy:
            - ADD _build/configs/ansible.cfg /etc/ansible/ansible.cfg
#         append_base:
#         append_galaxy:
          prepend_final:
            - RUN whoami
            - RUN cat /etc/os-release
            - RUN pip3 install --upgrade pip setuptools
          append_final:
            - RUN echo This is a post-install command
            - RUN ls -la /etc/ansible
            
  tasks:
    - name: Include ee_builder role
      ansible.builtin.include_role:
        name: infra.ee_utilities.ee_builder
```

```console (error)
# ERROR shortened for bvevity
"ERROR! Error when finding available api versions from automation_hub_comm (https://aap.example.com/api/galaxy/content/community/token=**********************) (HTTP Code: 404, Message: Not Found)"

# Results of generated ansible.cfg
$ cat ansible.cfg
[galaxy]
server_list = automation_hub_pub,automation_hub_cert,automation_hub_validated,automation_hub_comm
ignore_certs = true

[galaxy_server.automation_hub_cert]
url=https://aap.cms4u2eat.com/api/galaxy/content/rh-certified/token=**********

[galaxy_server.automation_hub_pub]
url=https://aap.cms4u2eat.com/api/galaxy/content/published/token=**********

[galaxy_server.automation_hub_comm]
url=https://aap.cms4u2eat.com/api/galaxy/content/community/token=**********

[galaxy_server.automation_hub_validated]
url=https://aap.cms4u2eat.com/api/galaxy/content/validated/token=**********



```

## STEPS TO REPRODUCE

```yaml (playbook/task)
ansible-playbook deploy_custom_ee.yml

```

```yaml (config/list/array/variables)
---
- name: Custom Execution Environment Builder
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    ee_validate_certs: false
    ee_base_registry_username: "{{ lookup('env', 'CONTROLLER_ADMIN_USER') }}"
    ee_base_registry_password: "{{ lookup('env', 'CONTROLLER_ADMIN_PASS') }}"
    ee_base_image: aap.example.com/ansible-automation-platform-25/ee-supported-rhel9:latest
    ee_registry_dest: aap.example.com/binbashroot
    ee_registry_username: "{{ lookup('env', 'CONTROLLER_ADMIN_USER') }}"
    ee_registry_password: "{{ lookup('env', 'CONTROLLER_ADMIN_PASS') }}"
    ee_ah_host: aap.example.com
    ee_ah_token: "{{ lookup('env', 'HUB_TOKEN') }}"     
    ee_builder_dir_clean: false
    ee_builder_dir: "."
    ee_image_push: true
    ee_pull_collections_from_hub: true
    ee_update_base_images: true
    ee_verbosity: 3
    ee_list:
      - name: aap-test-cms-ee-supported-rhel9:{{ ee_tag | default('v2.0') }}
        alt_name: AAP CMS SUPPORTED RHEL9 EE       
        images:
          base_image: 
            name: aap.example.com/ansible-automation-platform-25/ee-supported-rhel9:latest
        dependencies:     
          ansible_core:
            package_pip: ansible-core>=2.15.13
          ansible_runner:
            package_pip: ansible-runner
          system:
            - tar
            - unzip
            - bzip2
            - nmap
            - gcc
            - systemd-devel
            - python3-devel
            - python3.11-devel
            - libxml2-devel
            - libxslt-devel

          python: 
            - proxmoxer>=1.3.1
            - netaddr>=0.8.0
            - urllib3>=1.26.12
            - cryptography>=41.0.6
            - pyopenssl>=23.1.0
            - awxkit
            - pytz
            - python-dateutil
          galaxy:
            collections:
              - community.general
              - community.crypto
              - community.dns
#       build_items:
#         - files/
        build_files:
          - src: files/ansible.cfg
            dest: configs 
        build_steps:
          prepend_base:
            - RUN echo This is the prepend base command
          prepend_galaxy:
            - ADD _build/configs/ansible.cfg /etc/ansible/ansible.cfg
#         append_base:
#         append_galaxy:
          prepend_final:
            - RUN whoami
            - RUN cat /etc/os-release
            - RUN pip3 install --upgrade pip setuptools
          append_final:
            - RUN echo This is a post-install command
            - RUN ls -la /etc/ansible
            
  tasks:
    - name: Include ee_builder role
      ansible.builtin.include_role:
        name: infra.ee_utilities.ee_builder
```

[minimum complete verifiable example]: http://stackoverflow.com/help/mcve
